packages:
  - 'apps/*'
  - 'packages/*'

overrides:
  'next@16.2.11>postcss': 8.5.10
  'next@16.2.11>sharp': 0.35.0
  'exceljs@4.4.0>uuid': 11.1.1
  '@esbuild-kit/core-utils@3.3.2>esbuild': 0.25.12

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@aws-sdk/checksums@3.1000.19'
  - '@aws-sdk/client-s3@3.1092.0'
  - '@aws-sdk/core@3.976.0'
  - '@aws-sdk/credential-provider-env@3.972.60'
  - '@aws-sdk/credential-provider-http@3.972.62'
  - '@aws-sdk/credential-provider-ini@3.973.5'
  - '@aws-sdk/credential-provider-login@3.972.67'
  - '@aws-sdk/credential-provider-node@3.972.71'
  - '@aws-sdk/credential-provider-process@3.972.60'
  - '@aws-sdk/credential-provider-sso@3.973.4'
  - '@aws-sdk/credential-provider-web-identity@3.972.66'
  - '@aws-sdk/middleware-sdk-s3@3.972.65'
  - '@aws-sdk/nested-clients@3.997.34'
  - '@aws-sdk/s3-request-presigner@3.1092.0'
  - '@aws-sdk/token-providers@3.1092.0'

onlyBuiltDependencies:
  - esbuild
  - sharp
